# Generated by Django 3.1.1 on 2020-09-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoforms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='status',
            field=models.CharField(default='Submitted', max_length=20),
        ),
    ]
