# Generated by Django 3.1.1 on 2020-09-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoforms_app', '0002_workflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
