# Generated by Django 3.1.1 on 2020-10-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoforms_app', '0003_workflow_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='type',
            field=models.CharField(choices=[('N', 'Nanopore sequencing data'), ('I', 'Ilumina sequencing data')], default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='type',
            field=models.CharField(choices=[('Q', 'Quality'), ('A', 'Assembly'), ('H', 'Hybrid'), ('-', 'Other')], default='-', max_length=10),
        ),
    ]
